VSR: Move formatting into `replica.zig`
tigerbeetle/tigerbeetle pull request #128
Opened 2022-08-03 21:28 UTC by sentientwaffle

- Move formatting (from superblock) into `replica.zig`.
- Rewrite WAL formatting to be async (previously used `os.write()`).

Previously the `MessagePool` was owned by the `MessageBus`, but this introduced a circular dependency: `SuperBlock` requires a `MessagePool`, `MessageBus` requires `cluster`, `cluster` is retrieved from the `SuperBlock`. I resolved this by moving `MessagePool` out and passing `MessageBus` a reference to the pool.

The `MessageBus` is required by the `Replica`, but must be initialized outside because we support different implementations (for now — see https://github.com/coilhq/tigerbeetle/issues/71).
But it must be initialized _after_ the `SuperBlock` is opened, since it requires the `cluster`.

2022-08-03 22:19 UTC, kprotty commented
Nice resolution for the dependencies. `SuperBlock` could take in a `MessageBus` (it uses it primarily to get/unref messages in `SuperBlockClientTable`), but `MessagePool` was used instead as its easier to setup for testing than the former.

2022-08-03 22:36 UTC, sentientwaffle commented
Yeah, `MessagePool` is better for `SuperBlock` — `MessageBus` would cause a circular dependency because it requires the `cluster`. (Plus using the narrower dependency is preferable in general).

2022-08-03 22:51 UTC, kprotty approved these changes

2022-08-04 10:49 UTC, jorangreef requested changes
We need to guarantee alignment for Direct I/O and then perhaps there's an assertion in here that would fail if we call `format_wal_sectors()` more than once.

2022-08-04 10:49 UTC, jorangreef commented on src/main.zig
> +const ReplicaFormatter = vsr.ReplicaFormatter(Storage);
```suggestion
const ReplicaFormat = vsr.ReplicaFormatType(Storage);
```

For type constructors, we've started adding `Type` as a suffix, e.g. `StateMachineType`. This helps reduce the chance of shadowing at the call site. For example, you get `StateMachine` from a `StateMachineType` — this helped clean up the LSM quite nicely since we have so many generics there.

I would suggest `ReplicaFormat` as a name, describing the format type as a noun not as a verb, so it's a little broader, and also works if we extend `Format` to do things like inspection or diagnostics or update of a format, i.e. not only the task of formatting, but anything to do with working with a format.

2022-08-04 10:49 UTC, jorangreef commented on src/main.zig
> +const ReplicaFormatter = vsr.ReplicaFormatter(Storage);
For example, we may soon need to be able to take in a format, and then rewrite the replica index. This could be necessary when recovering a replica from a backup, where we copy the data file, rewrite the replica-specific index and then run the recovery protocol.

2022-08-04 10:49 UTC, jorangreef commented on src/main.zig
> +        errdefer message_bus.deinit();
Do we also want to call `deinit()` for `message_pool` and `replica` etc.?

2022-08-04 10:49 UTC, jorangreef commented on src/vsr/replica.zig
> +            replica_index: u8,
Nice change!

2022-08-04 10:49 UTC, jorangreef commented on src/vsr/replica.zig
> +        journal_write_buffer: []u8,
We need this buffer type to be aligned to a sector, and also allocated according to alignment. Otherwise, we may get EINVAL from the kernel because alignment is required for Direct I/O.

2022-08-04 10:49 UTC, jorangreef commented on src/vsr/replica.zig
> +        journal_write: Storage.Write = undefined,
We could rename the `journal_` prefixes here to `wal_` since we use that also a bit further down.

2022-08-04 10:49 UTC, jorangreef commented on src/vsr/replica.zig
> +        journal_write: Storage.Write = undefined,
Since we're only doing writes in this context, we could also just do `wal_offset`, `wal_buffer`.

2022-08-04 10:49 UTC, jorangreef commented on src/vsr/replica.zig
> +            const buffer = self.journal_write_buffer;
Better to “shrink the scope” to reduce probability of misuse, and rather use these directly inline without taking const references, to avoid introducing a variable into the scope, and to avoid potentially copying something to the stack (in general, not a problem here).

If these are renamed to `wal_offset` and `wal_buffer` then that will also make inlining them easier.

2022-08-04 10:49 UTC, jorangreef commented on src/vsr/replica.zig
> +            const write_size = vsr.format_journal(self.cluster, offset, buffer);
We could also just do `size` here since the context everywhere is for writing.

2022-08-04 10:49 UTC, jorangreef commented on src/vsr/replica.zig
> +                    buffer[0..write_size],
What are our expectations of the contents of the buffer that we are writing here, that `format_journal()` will ensure everything in the buffer is ready for writing up to `size`?

2022-08-04 10:49 UTC, jorangreef commented on src/vsr/replica.zig
> +            assert(self.journal_write_offset == config.journal_size_max);
I think this could fail? For example, if we have to call `format_wal_sectors()` several times?

2022-08-04 16:49 UTC, sentientwaffle commented on src/main.zig
> +const ReplicaFormatter = vsr.ReplicaFormatter(Storage);
> This helps reduce the chance of shadowing at the call site.

This is a great idea; it also allows you to easily grep the code for either the constructor or the type independently.

2022-08-04 16:53 UTC, sentientwaffle commented on src/main.zig
> +        errdefer message_bus.deinit();
`MessagePool` doesn't have a `deinit()` function. (This surprised me; I plan to add one when I have time).

Also, `MessageBus`'s `deinit()` is currently a no-op.

I'll add the call `deinit()` for `replica`.

2022-08-04 18:26 UTC, sentientwaffle commented on src/vsr/replica.zig
> +            assert(self.journal_write_offset == config.journal_size_max);
Oops, that should have been `<=`.

2022-08-04 19:25 UTC, sentientwaffle commented on src/vsr/replica.zig
> +                    buffer[0..write_size],
Yes. I'll add an assertion to check:

```zig

            const zeros = [_]u8{0} ** @sizeOf(Header);
            for (std.mem.bytesAsSlice(Header, self.wal_buffer[0..size])) |*header| {
                if (header.checksum == 0 and header.checksum_body == 0) {
                    // This is the (empty) body of a Prepare.
                    assert(std.mem.eql(u8, std.mem.asBytes(header), &zeros));
                } else {
                    assert(header.valid_checksum());
                    assert(header.command == .prepare or header.command == .reserved);
                    assert(header.op != 0 or header.operation == .root);
                }
            }
```

2022-08-04 19:39 UTC, merged