Client: Java ID generator helper
tigerbeetle/tigerbeetle pull request #1347
Opened 2023-12-11 04:25 UTC by kprotty

Creates a static helper function in the java client for generating thread-safe, unique, and monotonic `u128` IDs to use for Accounts and Transfers.

2023-12-14 00:19 UTC, batiati reviewed
Nice and elegant implementation!!!

Can we push the scope of this PR a little further and review the samples and docs to mention/use ULID where it's applicable?

2023-12-14 00:19 UTC, batiati commented on src/clients/java/src/main/java/com/tigerbeetle/UInt128.java
> +            if (randomLo++ == Long.MAX_VALUE && randomHi++ == 0xffff) {
Zig has spoiled me a lot 😇

- Can we drop the `++` operator in favor of `+=1`?

- It's a signed integer, did you really mean `Long.MAX_VALUE` here, or should it be `0xFFFFFFFFFFFFFFFF` ?

- It's safe to use `+ 1` with signed integers since Java allows arithmetic operations to overflow. But it's worthy of a comment.

2023-12-14 00:19 UTC, batiati commented on src/clients/java/src/test/java/com/tigerbeetle/UInt128Test.java
> +                        ulidB.assertMonotonicSince(ulidA);
Can we also use `UInt128.asBigInteger` to compare both ULIDs?
This will assert that the binary representation is really what we expect at Zig's side (a monotonically increasing `u128` little-endian).

```java
var bigIntA = UInt128.asBigInteger(...);
var bigIntB = UInt128.asBigInteger(...);
assertTrue(bigIntB.compareTo(bigIntA) > 0); 
```

2023-12-14 10:42 UTC, batiati commented on src/clients/java/src/main/java/com/tigerbeetle/UInt128.java
> +    public static byte[] ULID() throws ArithmeticException {
By convention unchecked exceptions should not be declared in the `throws` clause, but only documented.

```suggestion
    /**
     * Generates a Universally Unique Lexicographically Sortable Identifier
     * (<a href="https://github.com/ulid/spec">ULID</a>) as 16 bytes of a 128-bit value.
     *
     * The ULID returned always increases monotonically and is thread-safe.
     *
     * @throws ArithmeticException as per ULID specs, if the 80 bits of randomness overflows.
     * @return an array of 16 bytes representing the 128-bit value.
     */
    public static byte[] ULID() {
```

2023-12-14 17:18 UTC, kprotty commented on src/clients/java/src/test/java/com/tigerbeetle/UInt128Test.java
> +                        ulidB.assertMonotonicSince(ulidA);
Sort of: `asBigInteger` interprets the bytes as 2 little-endian u64 values of a u128. ULID however stores timestamp as `{u32, u16}` and random as u80, both big-endian. We can instead interpret the bytes directly via `new BigInteger(ULID())` since it assumes big-endian. This also means Zig side might not see it as monotonically increasing little-endian.

2024-01-19 17:30 UTC, kprotty commented on src/clients/java/src/test/java/com/tigerbeetle/UInt128Test.java
> +                        ulidB.assertMonotonicSince(ulidA);
`ULID` has been renamed to `ID` and it stores the individual fields in little-endian which allows use of `asBigInteger`.

2024-01-20 19:37 UTC, batiati requested changes
Just two minor comments, but LGTM other than that!

2024-01-20 19:37 UTC, batiati commented on src/clients/java/src/main/java/com/tigerbeetle/UInt128.java
> +                if (randomHi == 0xffff) {
Let's standardize hex in upper case.

```suggestion
                if (randomHi == 0xFFFF) {
```

2024-01-20 19:37 UTC, batiati commented on src/clients/java/src/main/java/com/tigerbeetle/UInt128.java
> +     * The ID() function is thread-safe, the bytes returned are formatted in little endian, and the
I think it's worth mentioning that this ID is based on the UILD spec, except it is little-endian, so it is binary sortable and not lexicographically sortable by the string representation. In fact, our version has no concept of string representation.

```suggestion
     * The ID() function is thread-safe, the bytes returned are stored in little endian, and the
```

2024-01-20 23:24 UTC, batiati submitted a review, later dismissed
Thanks King ✌️

2024-01-22 09:49 UTC, batiati approved these changes

2024-01-22 14:43 UTC, merged