Fix outdated client usage
tigerbeetle/tigerbeetle pull request #229
Opened 2022-10-28 23:32 UTC by batiati

Fixes:

- `benchmark.zig` did not check return codes, causing the program to ignore failed batches and report unrealistic performance measurements.

- Incorrect usage of zeroed values at `code=0` for account/transfer creation and `transfer.id=0` for the first transfer of the batch.

- `demo_01_create_accounts.zig` was creating a new account with `credits_posted=10000`, causing the operation to fail with `credits_posted_must_be_zero`.

**Notes**

As discussed with @sentientwaffle, I noticed the fields `ledger`, `code`, and `amount` **are allowed to be zero** as a convenience when posting/voiding transfers.

From[`demo_05_post_pending_transfers.zig`](https://github.com/tigerbeetledb/tigerbeetle/blob/main/src/demo_05_post_pending_transfers.zig#L7-L19)

It's worth noting that this feature is not mentioned anywhere in the documentation.

2022-10-28 23:34 UTC, sentientwaffle commented
Thanks @batiati! I'll review this when I get the chance. And I'm working on an update to the docs, which will include the `ledger`/`code`/`amount` fix.

2022-10-29 01:00 UTC, sentientwaffle requested changes
Great catch, @batiati!

2022-10-29 01:00 UTC, sentientwaffle commented on src/benchmark.zig
> +
```suggestion
                const create_accounts_results = std.mem.bytesAsSlice(tb.CreateAccountsResult, value);
                if (create_accounts_results.len > 0) {
                    log.err("CreateAccountsResults={any}", .{create_accounts_results});
                    @panic("Unexpected result creating accounts.");
                }
            },
            .create_transfers => {
                const create_transfers_results = std.mem.bytesAsSlice(tb.CreateTransfersResult, value);
                if (create_transfers_results.len > 0) {
                    log.err("CreateTransfersResults={any}", .{create_transfers_results});
                    @panic("Unexpected result creating transfers.");
                }

```

`{s}` is used to format a slice of bytes (`[]u8`) as a string, e.g. `[]u8{97, 98, 99}` becomes `"abc"`.

`{any}` is a more general "print slice of arbitrary type" format specifier — which is what we need here, to print slices of `CreateAccountsResult`/`CreateTransfersResult`.

2022-10-29 01:00 UTC, sentientwaffle commented on src/demo_01_create_accounts.zig
>          },
Can you omit this change from the PR? I included a fix for in https://github.com/tigerbeetledb/tigerbeetle/pull/224 that maintains `flags.debits_must_not_exceed_credits`.

2022-10-29 13:29 UTC, batiati commented on src/benchmark.zig
> +
Sure, I used `{s}` following the existing code, and actually, I was surprised to see that `{s}` even produced the expected formatted output!

```diff
- log.debug("response={s}", .{std.mem.bytesAsSlice(tb.CreateAccountsResult, value)});
```
I also searched the codebase for other incorrect usages of `{s}`, and I found none.

2022-10-29 14:10 UTC, sentientwaffle reviewed
Perfect; thank you!

2022-10-29 14:11 UTC, sentientwaffle approved these changes
I meant to approve this just now...

2022-10-29 14:11 UTC, merged