Add c_client step in zig build
tigerbeetle/tigerbeetle pull request #479
Opened 2023-02-19 18:41 UTC by v0idpwn

I think this would be useful in general. I'm still not 100% sure about the implementation, so I'm opening as a draft.

## Pre-merge checklist

Performance:
* [X] I am very sure this PR could not affect performance.

2023-02-19 19:13 UTC, v0idpwn commented on build.zig
> +        lib.setOutputDir("zig-out/lib/" ++ platform);
Plus, this :)

2023-02-20 09:39 UTC, batiati commented
Thanks for the PR.
In order to be useful for more use cases, we should output both the dynamically and statically linked libraries, plus `tb_client.h` in some specific dir (e.g. `/src/clients/c/lib`, added to git ignore). 

This output dir could be packed by the CI into a single artifact and made available for download.

2023-02-21 08:46 UTC, v0idpwn commented
Updated to include static library + headers and changed output directory. Will look into the CI part later.

2023-02-21 10:42 UTC, batiati requested changes
Great job, thank you for this PR.

It's OK to leave it out of the CI for now. We still have to figure out how we want to publish these artifacts, maybe along with the weekly release, but not sure yet.

2023-02-21 10:42 UTC, batiati commented on build.zig
> +    const build_step = b.step("c_client", "Build C client shared library");
Remove the word "shared"

2023-02-21 10:42 UTC, batiati commented on build.zig
> +        "x86_64-linux",
We need to build for both Linux ABI: gnu and musl

2023-02-21 10:42 UTC, batiati commented on build.zig
> +
remove this blank line

```suggestion
```

2023-02-22 14:50 UTC, kprotty commented
bors r+

2023-02-22 20:09 UTC, batiati requested changes

2023-02-22 20:09 UTC, batiati commented on build.zig
> +        "../src/clients/c/include/tb_client.h",
Let's keep all artifacts under a single output dir:

```suggestion
        "../src/clients/c/lib/include/tb_client.h",
```

2023-02-22 20:09 UTC, batiati commented on .gitignore
> +src/clients/c/include
No need for this one
```suggestion
```

2023-02-23 09:55 UTC, batiati commented
bors r+

2023-02-23 10:26 UTC, batiati approved these changes

2023-02-23 10:26 UTC, batiati commented
bors r+

2023-02-23 10:41 UTC, merged