fix: undefined reference to `__zig_probe_stack'
tigerbeetle/tigerbeetle pull request #792
Opened 2023-05-18 13:28 UTC by kassane

Allows another C compiler link to this library.

If the library allowed build `ReleaseFast` then this command would be useless.

cc: @batiati @kprotty 

**Reference:**
- https://github.com/ziglang/zig/issues/6817#issuecomment-736129115

> Now you can pass -fcompiler-rt to include compiler-rt in static libraries. Feel free to open a proposal to change the default, which is currently only dynamic libraries and executables get compiler-rt included. - **Andrewrk**

## Pre-merge checklist

* [x] I am very sure this PR could not affect performance.

2023-05-18 13:33 UTC, eatonphil commented
> If the library allowed build ReleaseFast then this command would be useless.

I'm pretty sure we have comptime checks that fail the build if you try to do ReleaseFast.

2023-06-21 15:00 UTC, batiati requested changes
Thanks Matheus,

It's worth adding a comment:

```zig
// Bundle rt to allow linking this static library
// with the final artifact using something other than Zig.
```

Could you please add `static_lib.pie = true` as well? So we follow the same configuration used by Go client's static libraries:

https://github.com/tigerbeetledb/tigerbeetle/blob/1c4000cbd5c4fb8c892019dd29787d1da0ae1e09/build.zig#L597-L598

2023-06-21 15:46 UTC, kassane commented
Hi @batiati ,

I have added the suggestion and the build has worked with gcc 13 (archlinux).
A doubt, does this change overwrite other bindings (duplicate parameters)?

At first sight, I think that the settings between bindings are standalone. Right?

2023-06-21 16:20 UTC, batiati commented
> A doubt, does this change overwrite other bindings (duplicate parameters)?
> At first sight, I think that the settings between bindings are standalone. Right?

I'm not sure if I'm following,  but the other bindings (clients) compile their libs independently, so it's not duplicated but only following the same build configuration for similar use cases (i.e. both c_client and go_client produce static libraries).

Did I get your question answered?

(...)

Maybe we can extract this part in a helper function, just like `link_tracer_backend` is called by every artifact, we can then create a `fn static_lib_config(...)` for doing that repetitive work of setting up correctly a static lib.

We can also place the comment there:

```Zig
// Bundle rt to allow linking this static library
// with the final artifact using something other than Zig.
```

Looking at the code, shared libs have even more repeated code, but it can be done by another PR!

2023-06-21 16:22 UTC, kassane commented
>Did I get your question answered?

Yeah!!

> Looking at the code, shared libs have even more repeated code, but it can be done by another PR!

Ok.

2023-06-21 22:06 UTC, batiati approved these changes

2023-06-21 22:14 UTC, merged