tb_client: expose the init function as public
tigerbeetle/tigerbeetle pull request #804
Opened 2023-05-24 21:13 UTC by rbino

The init function can now be used to initialize the client from Zig, using some more idiomatic Zig conventions, namely being able to pass an explicit allocator and using a slice instead of ptr + len for the addresses string. Add an additional c_client_init helper to factor out the code needed to adapt the C interface to the Zig init function.

## Pre-merge checklist

Performance:
* [x] I am very sure this PR could not affect performance.

2023-05-24 22:27 UTC, batiati requested changes
> as usual naming things is hard :smile:

It's a bit more work refactoring (tests and clients that uses zig code), but I just had an idea: what if we dropped the `tb_client` prefix for all functions and only exposed them with this naming convention in the export section?

We can encapsulate all FFI specifics into an inner struct, so there is no naming collision. 

Like this:
```zig

const ffi = struct {
    pub fn c_init( .... ) tb_status_t {
        // Any FFI translation goes here:
    }

    pub fn c_init_echo( ... ) tb_status_t {
        // Any FFI translation goes here:
    }
}

comptime {
    if (builtin.link_libc) {
        @export(ffi.c_init, .{ .name = "tb_client_init", .linkage = .Strong });
        @export(ffi.c_init_echo, .{ .name = "tb_client_init_echo", .linkage = .Strong });
        @export(acquire_packet, .{ .name = "tb_client_acquire_packet", .linkage = .Strong });
        @export(release_packet, .{ .name = "tb_client_release_packet", .linkage = .Strong });
        @export(submit, .{ .name = "tb_client_submit", .linkage = .Strong });
        @export(deinit, .{ .name = "tb_client_deinit", .linkage = .Strong });
    }
}
```

PS: Don't worry about the failing CI, some checks fail when the PR comes from a branch in another repository.

2023-05-24 22:27 UTC, batiati commented on src/clients/c/tb_client.zig
> +    _ = allocator;
Pointless discard

2023-05-25 20:52 UTC, rbino commented
@batiati implemented your suggestion above, let me know if that's what you had in mind

2023-05-26 14:35 UTC, batiati requested changes
Thank you, @rbino
Just two minor adjustments, and we are good to merge 🎉

2023-05-26 14:35 UTC, batiati commented on src/clients/java/src/client.zig
> +        var msg = std.fmt.bufPrintZ(&buf, "{s}", .{@errorName(err)}) catch {
We can't do that, our `InitializationException` class expects an integer value on the constructor, that's why we don't use `env.throwNew` but instead we construct a new instance.

We should use the function `context_error_to_status` here, and keep passing the integer value to the Java side.

2023-05-26 14:35 UTC, batiati commented on src/clients/c/tb_client.zig
> +fn init_with_context(
I think it's ok to repeat the pattern `Context.init( ... ) catch |err| return context_error_to_status(err);`. We don't need an `init_with_context` function.

2023-05-26 23:13 UTC, batiati approved these changes
Grazie Riccardo 😎👨‍🍳🤌

2023-05-27 11:35 UTC, merged